<?php

/**
 * Auto-generated by OS2Web Logging settings form.
 * Do not edit manually.
 */

$settings['os2web_logging.watchdog_dblog_enabled'] = NULL;
$settings['os2web_logging.watchdog_files_log_path'] = NULL;
$settings['os2web_logging.watchdog_files_store_period'] = NULL;
