<?php

/**
 * Auto-generated by OS2Web Logging settings form.
 * Do not edit manually.
 */

$settings['os2web_logging.files_log_path'] = '../logs';
$settings['os2web_logging.files_store_period'] = '180';
