<?php


function bc_ldap_userimport_cron() {
    $config = (object) \Drupal::config('bc_ldap_userimport.settings')->get();
    if ($config->enabled && $config->cron) {
        $run = true;
        $lastrun = $config->lastrun ?? null;
        if (!empty($lastrun)) {
            $compare = null;
            switch ($config->run) {
                case '': $run = false; echo "empty\n"; break;
                case 'day': $compare = strtotime("+1 day 00:00:00", $config->lastrun); break;
                case 'week': $compare = strtotime("+1 week 00:00:00", $config->lastrun); break;
                case 'month': $compare = strtotime("+1 month 00:00:00", $config->lastrun); break;
            }
            if ($compare > time()) {
                $run = false;
            }
        }

        if ($run) {
            $li = new \Drupal\bc_ldap_userimport\Controller\LdapImport();
            $data = $li->getData();
            $data = $li->trimData($data);
            $queue = \Drupal::service('queue')->get('ldap_user_import_queue');
            foreach ( $data AS $idx => $user ) {

                if (!empty($user->samaccountname)) $user->samaccountname = strtolower($user->samaccountname);
                if (!empty($user->mail)) $user->mail = strtolower($user->mail);
                if (!empty($user->displayname)) $user->displayname = utf8_decode($user->displayname);
                if (!empty($user->name)) $user->name = utf8_decode($user->name);
                if (!empty($user->dn)) $user->dn = utf8_decode($user->dn);
                if (!empty($user->memberof) && is_array($user->memberof)) {
                    foreach ( $user->memberof AS &$member ) $member = utf8_decode($member);
                }

                $queue->createItem($user);
            }

            $saveConfig = \Drupal::configFactory()->getEditable('bc_ldap_userimport.settings');
            $saveConfig->set('lastrun', time())->save();
        }
    }
}



