<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Response;

/**
 * Implements hook_menu() for Drupal 9 page callback.
 */
function bc_webdav_manager_menu() {
  $items = [];

  $items['document-handle'] = [
    'title' => 'Document handling',
    'description' => 'Document handler page',
    'route_name' => 'bc_webdav_manager.webdav_controller_page',
  ];

  $items['admin/config/system/bc-webdav-manager'] = [
    'title' => 'RK Webdav manager',
    'description' => 'Specify location for webdav',
    'page_callback' => 'drupal_get_form',
    'page_arguments' => ['bc_webdav_manager_form'],
    'type' => MENU_NORMAL_ITEM,
    'access_arguments' => ['administer site configuration'],
  ];

  return $items;
}

/**
 * Implements hook_form() for Drupal 9 form.
 */
function bc_webdav_manager_form($form, FormStateInterface $form_state) {
  $config = \Drupal::config('bc_webdav_manager.settings');

  $form['bc_webdav_manager_form_outsite_location_textfield'] = [
    '#type' => 'textfield',
    '#title' => t('Webdav location outside'),
    '#default_value' => $config->get('outsite_location_textfield'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
    '#description' => 'The full path the webdav for outside editing eg: http://dev.midtpunktet.ringsted.dk/webdav/',
  ];

  $form['bc_webdav_manager_form_submit'] = [
    '#type' => 'submit',
    '#value' => t('Save'),
  ];

  return $form;
}

/**
 * Form submission handler for the Drupal 9 form.
 */
function bc_webdav_manager_form_submit(array $form, FormStateInterface $form_state) {
  \Drupal::configFactory()
    ->getEditable('bc_webdav_manager.settings')
    ->set('outsite_location_textfield', $form_state->getValue('bc_webdav_manager_form_outsite_location_textfield'))
    ->save();

  $this->messenger()->addMessage("Saved!");
}

function bc_webdav_manager_entity_extra_field_info () {
  return [
    'node' => [
      'file' => [
        'display' => [
          'download_link' => [
            'label' => t('Download link'),
            'description' => t('Download link'),
            'weight' => 100,
            'visible' => TRUE,
          ],
          'view_link' => [
            'label' => t('View link'),
            'description' => t('View link'),
            'weight' => 101,
            'visible' => TRUE,
          ],
          'edit_link' => [
            'label' => t('Edit link'),
            'description' => t('Edit link'),
            'weight' => 102,
            'visible' => TRUE,
          ],
        ],
      ],
    ],
  ];
}

function bc_webdav_manager_node_view(array &$build,
                                    \Drupal\Core\Entity\EntityInterface $entity,
                                    \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display,
                                    $view_mode) {

  // Get the node
  $node = \Drupal::routeMatch()->getParameter('node');

  // Generate download link
  if ($entity->bundle() === 'file'
    && $display->getComponent('download_link')) {
    $file_uri = $node->field_file->entity->getFileUri();
    $file_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);

    // Build the link
    $build['download_link'] = [
      '#url' => \Drupal\Core\Url::fromUri($file_url),
      '#title' => "Download",
      '#type' => 'link',
    ];
  }

  // Generate view link
  if ($entity->bundle() === 'file'
    && $display->getComponent('view_link')) {

    $file_uri = $node->field_file->entity->getFileUri();
    $file_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);

    // Build the link
    $build['view_link'] = [
      '#url' => \Drupal\Core\Url::fromUri($file_url),
      '#title' => "View",
      '#type' => 'link',
    ];

  }

  // Generate view link
  if ($entity->bundle() === 'file'
    && $display->getComponent('edit_link')) {

    $file_uri = $node->field_file->entity->getFileUri();
    $file_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);

    // Build the link
    $build['view_link'] = [
      '#url' => 'ms-word:ofe|u|' . $file_url,
      '#title' => "Edit",
      '#type' => 'link',
    ];

  }
}
