<?php


/**
 * Implements hook_theme().
 */
function bc_flag_extension_theme($existing, $type, $theme, $path) {

  $config = \Drupal::config('bc_flag_extension.settings')->get();
  unset( $config['submit'], $config['form_build_id'], $config['form_token'], $config['form_id'], $config['op']);

  if (!empty($config['enabled'])) {

    $vars = array(
      'name' => '',
      'loggedin' => false,
      'bookmarks' => array(),
      'shortcuts' => array(),
      'unreads' => array()
    );

    $items = array(
        'sidebar' => array(
            'render element' => 'element',
            'template' => 'sidebar',
            'variables' => array(
                'vars' => $vars,
                'config' => $config
            )
        )
    );

    return $items;

  }
}


/**
 * Implements hook_preprocess_HOOK().
 */
function bc_flag_extension_preprocess_page(&$variables) {

  // unflagging unread flag if is node flag is set for this user
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    if (!$user->isAnonymous()) {
      $flagService = \Drupal::service('flag');
      $flag = $flagService->getFlagById('unread');
      if ($flag) {
        $flagging = $flagService->getFlagging($flag, $node, $user);
        if ($flagging) {
          $flagService->unflag($flag, $node, $user);
        }
      }
    }

    $variables['#attached']['drupalSettings']['data']['nid'] = $node->id();


  }
}

