<?php

use Drupal\bc_basic\Debug;
use Drupal\Core\Cache\CacheableMetadata;

use Drupal\Core\Url;
use Drupal\og\Og;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

function bc_og_extension_views_data() {

  $data = array();

  $data['og_membership'] = array(
    'og_node' => array(
      'relationship' => array(
        'title' => 'OG node relation',
        'base' => 'node_field_data',
        'base field' => 'nid',
        'field' => 'entity_id',
        'handler' => 'views_handler_relationship',
        'id' => 'standard',
        'help' => 'OG entity ID relation to the node',
      )
    ),
    'og_user' => array(
      'relationship' => array(
        'title' => 'OG user relation',
        'base' => 'users_field_data',
        'base_field' => 'uid',
        'field' => 'uid',
        'handler' => 'views_handler_relationship',
        'id' => 'standard',
        'help' => 'OG user ID relation to the user',
      )
    )
  );

  return $data;


}


function bc_og_extension_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  if (
    ($view->id() === 'organic_groups') &&
    (
      ($view->current_display == 'other_groups_block') ||
      ($view->current_display == 'other_projects_block')
    )
  ) {

    $user = \Drupal::currentUser();
    if (!$user->isAnonymous()) {
      $sql = "
        SELECT
            entity_id
        FROM
            og_membership
        WHERE
            uid={$user->id()} AND
            entity_type='node' AND
            (entity_bundle='group' OR entity_bundle='gruppe') AND
            (state='active')
        ;";

      $entitieIds = \Drupal::database()
        ->query($sql)
        ->fetchAllKeyed(0, 0);

      if (count($entitieIds)) {
        $entitieIds = array_values($entitieIds);
        foreach ($query->where as &$condition_group) {
          foreach ($condition_group['conditions'] as &$condition) {
            if ($condition['field'] == 'og_membership.entity_id') {
              $condition['value'] = $entitieIds;
              $condition['operator'] = 'NOT IN';
            }
          }
        }
      }
    }
  }

  if ($view->id() === 'organic_groups' && $view->current_display === 'group_member_tab') {

    $nodeid = null;
    $current_path = \Drupal::service('path.current')->getPath();
    $path = (explode('/', $current_path));
    array_pop($path);
    $path = implode('/', $path);

    $alias = \Drupal::service('path_alias.manager')->getPathByAlias($path);
    if (preg_match('/node\/(?P<id>\d+)/', $alias, $matches)) {
      $node = \Drupal\node\Entity\Node::load($matches['id']);
      if ($node instanceof Drupal\node\Entity\Node) $nodeid = $node->id();
    }

    if ($nodeid) {
      foreach ($query->where as &$condition_group) {
        foreach ($condition_group['conditions'] as &$condition) {
          if (isset( $condition['value'][':node_field_data_nid'] )) {
            $condition['value'][':node_field_data_nid'] = $nodeid;
          }
        }
      }

    }
  }

}


/**
 * Implements hook_theme().
 */
function bc_og_extension_theme($existing, $type, $theme, $path) {
  return array(
    'views_view_unformatted__organic_groups__my_groups_block' => array(
      'template' => 'views-view-unformatted--organic-groups--my-groups-block',
      'base hook' => 'view'
    ),
    'views_view_unformatted__organic_groups__all_groups_block' => array(
      'template' => 'views-view-unformatted--organic-groups--all-groups-block',
      'base hook' => 'view'
    ),
    'views_view_unformatted__organic_groups__other_groups_block' => array(
      'template' => 'views-view-unformatted--organic-groups--other-groups-block',
      'base hook' => 'view'
    ),
    'views_view_unformatted__organic_groups__my_projects_block' => array(
      'template' => 'views-view-unformatted--organic-groups--my-projects-block',
      'base hook' => 'view'
    ),
    'views_view_unformatted__organic_groups__all_projects_block' => array(
      'template' => 'views-view-unformatted--organic-groups--all-projects-block',
      'base hook' => 'view'
    ),
    'views_view_unformatted__organic_groups__other_projects_block' => array(
      'template' => 'views-view-unformatted--organic-groups--other-projects-block',
      'base hook' => 'view'
    ),
    'views_view_unformatted__organic_groups__latest_groups_block' => array(
      'template' => 'views-view-unformatted--organic-groups--latest-groups-block',
      'base hook' => 'view'
    ),
  );

}


/**
 * Implements hook_theme().
 */
function bc_og_extension_views_pre_render(ViewExecutable $view) {

  if ($view->id() === 'organic_groups') {
    $currentUser = \Drupal::currentUser();
    $currentUserId = null;
    if (!$currentUser->isAnonymous()) {
      $currentUser = \Drupal\user\Entity\User::load($currentUser->id());
      $currentUserId = $currentUser->id();
    }

    $flagService = \Drupal::service('flag');
    $unreadFlag = $flagService->getFlagById('unread');

    foreach ($view->result as $key => $value) {

      if ($value->_relationship_entities && !empty($value->_relationship_entities['og_node'])) {

        $node = $value->_relationship_entities['og_node'];
        $isMember = false;
        $isAdmin = false;
        $member_status = null;
        $unread = 0;

        if ($currentUserId) {
          $isMember = Og::isMember($node, $currentUser);
          if ($isMember) {
            $memberShip = Og::getMembership($node, $currentUser);
            $isAdmin = $memberShip->hasRole('node-group-administrator');
            $member_status = $memberShip->getState();

            if ($view->current_display === 'my_groups_block') {
              $groupcontents = \Drupal::entityTypeManager()
                ->getStorage('node')
                ->loadByProperties([
                  'type' => 'og_group_content',
                  'og_audience' => $node->id(),
                ]);

              if (count($groupcontents) > 0) {
                foreach ($groupcontents as $groupcontent) {
                  $hasContentFlag = $flagService->getFlagging($unreadFlag, $groupcontent, $currentUser);
                  if ($hasContentFlag) $unread++;
                }
              }

            }
          }
        }

        $value->data = (object) array(
          "nid" => $node->id(),
          "title" => $node->getTitle(),
          "cuid" => $currentUserId,
          "is_admin" => $isAdmin,
          "is_member" => $isMember,
          "member_status" => $member_status,
          "unread" => $unread
        );

      }
    }

  }

}


/**
 * Implements hook_form_alter().
 */
function bc_og_extension_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $input = $form_state->getUserInput();
  if (!empty($input) && !empty($input['confirm'])) {

    if ($form_id == 'og_subscribe_confirm_form') {

      $formObject = $form_state->getFormObject()->getEntity();
      $nodeId = $formObject->get('entity_id')->value;
      $userId = $formObject->get('uid')->target_id;

      $node = $node = \Drupal::entityTypeManager()->getStorage('node')->load($nodeId);
      $user = \Drupal\user\Entity\User::load($userId);

      if (Og::isGroup($node->getEntityTypeId(), 'group')) {

        $config = \Drupal::config('bc_og_extension.settings')->get();
        if ($config['default_active']) {
          $form['state']['widget']['#default_value'] = 'Active';
        }

        $view = Views::getView('organic_group_content');
        if (is_object($view)) {
          $view->setDisplay('list');
          $view->setArguments(array($node->id()));
          $view->execute();

          $flagService = \Drupal::service('flag');
          $flag = $flagService->getFlagById('unread');
          if ($flag) {
            foreach ($view->result as $row) {

              $group_content = \Drupal::entityTypeManager()
                ->getStorage('node')
                ->load($row->nid);

              $flagging = $flagService->getFlagging($flag, $group_content, $user);
              if (!$flagging) {
                $flagService->flag($flag, $group_content, $user);
              }
            }
          }
        }
      }

    } elseif ($form_id == 'og_unsubscribe_confirm_form') {

      $formObject = $form_state->getFormObject()->getEntity();
      $nodeId = $formObject->get('entity_id')->value;
      $userId = $formObject->get('uid')->target_id;

      $node = $node = \Drupal::entityTypeManager()
        ->getStorage('node')
        ->load($nodeId);
      $user = \Drupal\user\Entity\User::load($userId);

      if (Og::isGroup($node->getEntityTypeId(), 'group')) {

        $view = Views::getView('organic_group_content');
        if (is_object($view)) {
          $view->setDisplay('list');
          $view->setArguments([$node->id()]);
          $view->execute();

          $flagService = \Drupal::service('flag');
          $flag = $flagService->getFlagById('unread');
          if ($flag) {
            foreach ($view->result as $row) {

              $group_content = \Drupal::entityTypeManager()
                ->getStorage('node')
                ->load($row->nid);

              $flagging = $flagService->getFlagging($flag, $group_content, $user);
              if ($flagging) {
                $flagService->unflag($flag, $group_content, $user);
              }
            }
          }
        }
      }
    }
  }

  if ($form['#id'] == 'views-exposed-form-organic-groups-og-group-member') {
    if (isset($form['groupselect'])) {

      $view = \Drupal\views\Views::getView('organic_groups');
      $view->setDisplay('all_groups_block');
      $view->execute();
      $groups = array('gruppe valg');
      foreach ($view->result as $fid => $row) {

        $nid = null;
        $name = null;
        foreach ($view->field as $fid => $field) {
          if ($fid == 'title') $name = $field->getValue($row);
          if ($fid == 'nid') $nid = $field->getValue($row);
        }
        if ($nid && $name)  $groups[$nid] = $name;
      }
    }

    $form['groupselect']['#type'] = 'select';
    $form['groupselect']['#options'] = $groups;
    $form['groupselect']['#size'] = 1;
    $form['groupselect']['#default_value'] = 0;
  }

}



function bc_og_extension_node_insert(\Drupal\node\NodeInterface $node) {

  // if new group content, add to user in this group unread list
  if (Og::isGroupContent($node->getEntityTypeId(), $node->getType())) {

    $groupID = $node->get('og_audience')->target_id;
    $group = \Drupal::entityTypeManager()->getStorage('node')->load($groupID);
    if ($group) {
      $sql = "
        SELECT
            uid
        FROM
            og_membership
        WHERE
            entity_id={$group->id()} AND
            entity_type='node' AND
            entity_bundle='group' AND
            (state='active')
        ;";

      $userIds = \Drupal::database()
        ->query($sql)
        ->fetchAllKeyed(0, 0);

      if (count($userIds) > 0) {
        $flagService = \Drupal::service('flag');
        $flag = $flagService->getFlagById('unread');
        if ($flag) {
          foreach ($userIds as $userId) {
            $user = \Drupal\user\Entity\User::load($userId);
            $flagging = $flagService->getFlagging($flag, $node, $user);
            if (!$flagging) {
              $flagService->flag($flag, $node, $user);
            }
          }
        }
      }
    }
  }

}
