<?php

use Drupal\og\Og;

function bc_og_extension_views_data() {

  $data = array();

  $data['og_membership'] = array(
    'entity_id' => array(
      'relationship' => array(
        'title' => 'OG node relation',
        'base' => 'node_field_data',
        'base_field' => 'nid',
        'field' => 'entity_id',
        'handler' => 'views_handler_relationship',
        'id' => 'standard',
        'help' => 'OG entity ID relation to the node',
      )
    ),
    'uid' => array(
      'relationship' => array(
        'title' => 'OG user relation',
        'base' => 'users_field_data',
        'base_field' => 'uid',
        'field' => 'uid',
        'handler' => 'views_handler_relationship',
        'id' => 'standard',
        'help' => 'OG user ID relation to the user',
      )
    )
  );

  return $data;


}


function bc_og_extension_views_query_alter(\Drupal\views\ViewExecutable $view, \Drupal\views\Plugin\views\query\QueryPluginBase $query) {

    if (($view->id() === 'organic_groups') && ($view->current_display == 'other_groups_block')) {
        $user = \Drupal::currentUser();
        if (!$user->isAnonymous()) {
            $sql = "
            SELECT 
                entity_id
            FROM
                og_membership
            WHERE
                uid={$user->id()} AND
                entity_type='node' AND
                entity_bundle='gruppe' AND
                state='active'
            ;";
            $entitieIds = \Drupal::database()
                ->query($sql)
                ->fetchAllKeyed(0, 0);
            if (count($entitieIds)) {
                $entitieIds = array_values($entitieIds);
                foreach ($query->where as &$condition_group) {
                    foreach ($condition_group['conditions'] as &$condition) {
                        if ($condition['field'] == 'og_membership.entity_id') {
                            $condition['value'] = $entitieIds;
                            $condition['operator'] = 'NOT IN';
                        }
                    }
                }
            }
        }
    }

}
