<?php


/**
 * Implements hook_node_presave().
 */
function bc_mail_smsmail_node_presave($node) {

  $conf = (object) \Drupal::config('bc_mail_smsmail.settings')->get();

  // if sms is enabled
  if (!empty($conf) && is_object($conf) && $conf->enabled && !empty($conf->gateway)) {

    // if node type is enabled
    $currentNodeType = $node->getType();
    if (isset($conf->contents[$currentNodeType]) && $conf->contents[$currentNodeType]['enabled']) {

      // if sms is enabled on the node and the node is new
      if ($node->hasField('field_text') && $node->get('field_text')->value && $node->isNew()) {

        $body = '';
        if ($node->hasField('body')) {
          $body .= $node->get('body')->value . "\r\n";
        }
        if ($node->hasField('field_os2web_page_heading')) {
          $body .= $node->get('field_os2web_page_heading')->value . "\r\n";
        }
        if ($node->hasField('field_os2web_page_intro')) {
          $body .= $node->get('field_os2web_page_intro')->value . "\r\n";
        }
        if ($node->hasField('field_os2web_page_description')) {
          $body .= $node->get('field_os2web_page_description')->value . "\r\n";
        }
        if ($node->hasField('field_os2web_system_page_content')) {
          $body .= $node->get('field_os2web_system_page_content')->value . "\r\n";
        }

        $body = "Ny driftbesked fra Midtpunktet" . "\r\n \r\n" .  strip_tags($body);

        $mailManager = \Drupal::service('plugin.manager.mail');
        $params = array(
          'subject' => 'Ny driftbesked fra Midtpunktet',
          'body' => array($body),
          'headers' => array(
            'From: ' . $conf->from,
            'Content-Type:' . 'text/html; charset=UTF-8; format=flowed; delsp=yes',
            'Reply-to: ' . $conf->reply . 'noreply@ringsted.dk',
            'X-Mailer: ' . 'PHP/' . phpversion()
          )
        );

        $sql = "
        SELECT 
            users_field_data.name,
            users_field_data.mail,
            users_field_data.status,
            field_driftbeskeder_sms_mobil_nr_value as mobil            
        FROM
            user__field_driftbeskeder_sms_mobil_nr
            RIGHT JOIN users_field_data ON (users_field_data.uid=user__field_driftbeskeder_sms_mobil_nr.entity_id)
        WHERE
            field_driftbeskeder_sms_mobil_nr_value IS NOT NULL AND
            deleted=0
        ;";

        $mobiles = \Drupal::database()
          ->query($sql)
          ->fetchAll();

        foreach ($mobiles as $idx => $member) {

          if ($member->status) {

            $result = $mailManager->mail(
              'bc_mail_smsmail',
              'operation',
              $member->mobil . $conf->gateway,
              'da',
              $params,
              $conf->reply,
              true
            );

            if ($result['result'] !== true) {
              \Drupal::logger('bc_mail_smsmail')->notice('operations sms not be sent to ' . $member->name . " , " .$member->mobil);
            } else {
              \Drupal::logger('bc_mail_smsmail')->notice('operations sms is sent to ' . $member->name . " , " . $member->mobil);
            }

          }
        }

      }
    }
  }

}

/**
 * Implements hook_mail().
 */
function bc_mail_smsmail_mail($key, &$message, $params) {

  if ($key === 'operation') {
    if (!empty($params['subject'])) $message['subject'] = $params['subject'];
    if (!empty($params['body']) && is_array($params['body'])) $message['body'] = $params['body'];
  }

}


