<?php

use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\File\FileExists;
use Drupal\file\IconMimeTypes;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Response;
use Drupal\Core\Link;


function bc_webdav_theme($existing, $type, $theme, $path) {
  return array(
    'file_link_webdav' => array(
      'template' => 'file-link-webdav',
      'base hook' => 'file link'
    ),
  );

}


function bc_webdav_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'bc_webdav/webdav-styling';
}


function bc_webdav_theme_suggestions_alter(array &$suggestions, array &$variables, $hook) {

  if ($hook === 'file_link') {

    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface && $node->bundle() == 'group_file') {
      if ($node->hasField('field_webdav') && $node->get('field_webdav')->value) {

        $file = $variables['file'];

        $mime_type = strtr($file->getMimeType(), ['/' => '-', '.' => '-']);

        $icon_classes = array(
          'file',
          'file--mime-' . $mime_type,
          'file--' . IconMimeTypes::getIconClass($file->getMimeType()),
          'webdav-file-link'
        );
        $variables['icon_classes'] = $icon_classes;

        $options = [];
        $options['attributes']['type'] = $file->getMimeType();

        if (empty($variables['description'])) {
          $link_text = $file->getFilename();

        } else {
          $link_text = $variables['description'];
          $options['attributes']['title'] = $file->getFilename();
        }

        $variables['link_text'] = $link_text;

        $file_url_generator = \Drupal::service('file_url_generator');
        $url = $file_url_generator->generate($file->getFileUri());
        $link = Link::fromTextAndUrl($link_text, $url->mergeOptions($options))->toRenderable();

        $variables['link'] = $link;

        $buttons = '<div class="webdav-buttons">';
        $buttons .= '<div class="webdav-button webdav-download" data-action="download" data-link="" data-id="' . $file->uuid() . '" title="download"></div>';
        $buttons .= '<div class="webdav-button webdav-view" data-action="view" data-link="" data-id="' . $file->uuid() . '" title="view"></div>';
        $buttons .= '<div class="webdav-button webdav-edit" data-action="edit" data-link="" data-id="' . $file->uuid() . '" data-locked="" title="edit"></div>';
        $buttons .= '<div class="webdav-button webdav-history" data-action="history" data-link="" data-id="' . $file->uuid() . '" title="history"></div>';
        $buttons .= '<iframe id="webdavframe" src="/webdavhandler" style="display:none"></iframe>';
        $buttons .= '</div>';

        $variables['buttons'] = array(
          '#type' => 'inline_template',
          '#template' => $buttons
        );

        $suggestions = array($hook . '_' . 'webdav');
      }
    }
  }
}


/**
 * Implements hook_cron().
 */
function bc_webdav_cron() {

  $config = (object) \Drupal::config('bc_webdav.settings')->get();
  if ($config->enabled && !empty($config->folder)) {

    foreach( glob($config->folder . '/*') as $filename) {
      if (!preg_match('/id./', $filename)) {

        $base = basename($filename);
        $dir = dirname($filename);

        $lastmodified = filemtime($filename);
        // waite at least 30 min before update
        if (time() < ($lastmodified + 1800)) {
          continue;
        }

        if (!file_exists($dir . '/id.' . $base)) {
          unlink($filename);
        } else {

          [$FileId, $UserId] = explode(":", file_get_contents($dir . '/id.' . $base));

          if (is_int(intval($FileId)) && is_int(intval($UserId))) {

            $files = \Drupal::entityTypeManager()
              ->getStorage('file')
              ->loadByProperties(['fid' => intval($FileId)]);

            if (!empty($files)) {

              $file = reset($files);
              if ($file->label() === $base) {

                $fileRepository = \Drupal::service('file.repository');
                $result = $fileRepository->writeData(file_get_contents($filename), $file->uri->value, FileExists::Replace);
                $result->save();

                unlink($filename);

                $account = \Drupal\user\Entity\User::load(intval($UserId));

                $connection = \Drupal::service('database');
                $connection->insert('bc_webdav_log')
                  ->fields([
                    'fid' => $file->id(),
                    'uid' => $account->id(),
                    'action' => 'update'
                  ])
                  ->execute();

              }
            } else unlink($filename);
          } else unlink($filename);
        }

      }
    }
  }

}